baseURL: https://chanon-r-blog.netlify.com/
disablePathToLower: true
languageCode: th
title: CHANON R. BLOG...
thumbnail: https://
theme: lazy
paginate: 12
permalinks:
  post: /:year/:month/:day/:slug/
pygmentsStyle: "dracula"
pygmentsCodefences: true
ignoreFiles:
  - "_drafts"
blackfriday:
  extensionsmask:
    - noIntraEmphasis
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: keywords
    weight: 100
  - name: date
    weight: 10
